version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/wordpress/

hooks:
  ApplicationStop:
    - location: scripts/stopserver.sh
      timeout: 50
  AfterInstall:
    - location: scripts/permission.sh
  ApplicationStart:
    - location: scripts/startserver.sh
      timeout: 50
